name: Atrap
version: '0.01'
main: mrhamzaless.com.atrap.Atrap
api-version: '1.18'
load: STARTUP
authors: [ MrHamzaless ]
website: https://mrhamzaless.xyz/

commands:
  atrap:
    description: Main command for Trap plugin.
